import { NOUNS, counted } from "@/lib/labels";
import { arabicNumber } from "@/lib/numerals";

/**
 * Every word the whiteboard shows (spec 039, constraint 8: «all strings via
 * i18n»). One object instead of an i18n library: the app is Arabic-only and has
 * no i18n system (R-16) — this keeps no string scattered in a component, and
 * moving to a library later replaces one import.
 *
 * A counted noun is a FUNCTION through `counted()`, never a template literal
 * («٢ صفحة» shipped elsewhere in this tree and was reported).
 */
export const WB = {
  board: "السبّورة",
  boards: "السبّورات",
  untitled: "سبّورة بلا عنوان",
  loading: "جارٍ تحميل السبّورة…",
  loadingFont: "جارٍ تحميل الخطّ العربي…",
  loadFailed: "تعذّر فتح السبّورة. تحقّق من الاتصال ثم أعد المحاولة.",
  notFound: "هذه السبّورة غير موجودة أو ليست لك.",

  newBoard: "سبّورة جديدة",
  rename: "إعادة التسمية",
  title: "عنوان السبّورة",
  background: "لون الصفحة",
  backgrounds: { white: "بيضاء", blackboard: "سبّورة سوداء", greenboard: "سبّورة خضراء" },
  save: "حفظ",
  cancel: "إلغاء",

  previousPage: "الصفحة السابقة",
  nextPage: "الصفحة التالية",
  screenUp: "أعلى",
  screenDown: "أسفل",
  screenNew: "مكان فارغ",
  screenOf: (screen: number, total: number) => `شاشة ${arabicNumber(screen)} من ${arabicNumber(total)}`,
  screens: "شاشات الصفحة",
  pageOf: (page: number, total: number) => `${arabicNumber(page)} من ${arabicNumber(total)}`,
  pages: (n: number) => counted(n, NOUNS.pages),
  boardsCount: (n: number) => counted(n, NOUNS.boards),

  export: "تصدير الصفحة",
  exportPng: "PNG",
  exportJpg: "JPG",
  exportSvg: "SVG",
  exporting: "جارٍ التصدير…",
  exportFailed: "تعذّر التصدير. أعد المحاولة.",

  present: "عرض",
  stopPresenting: "إنهاء العرض",
  presentHint: "تظهر الأدوات حين تقترب بالمؤشّر من أعلى الشاشة.",
  shareHint: "شارك هذا التبويب وحده، لا الشاشة كلها.",
  /** Story 7: the button in the live class. */
  live: {
    open: "افتح السبّورة",
    choose: "سبّورة لهذه الحصة",
    pick: "اختر سبّورة من سبّوراتك",
    linkAndOpen: "اربطها وافتحها",
    create: "سبّورة جديدة لهذه الحصة",
    failed: "تعذّر فتح السبّورة. أعد المحاولة.",
  },

  /** T096: the lesson editor's own boards. */
  lessonBoards: {
    title: "سبّورات الدرس",
    empty: "لا سبّورات لهذا الدرس بعد.",
    open: "افتح",
    create: "سبّورة جديدة لهذا الدرس",
    failed: "تعذّر إنشاء السبّورة. أعد المحاولة.",
    loadFailed: "تعذّر تحميل سبّورات الدرس. حدّث الصفحة.",
  },

  /** The toolbar's menus. */
  // «أدوات العرض», not «عرض»: the panel's own «عرض» button already says that word.
  menus: { tools: "أدوات", present: "أدوات العرض", encourage: "تشجيع", layout: "الواجهة", import: "استيراد", lesson: "مواد الدرس" },
  /** The board panel, folded by default (2026-10-03). */
  panel: { unfold: "افتح لوحة التحكم", fold: "اطوِ لوحة التحكم", pages: "التنقّل بين الصفحات" },
  /** Story 4 — a PDF or a picture added as pages after the page shown. */
  /** Story 6: a table, drawn from its cells and edited again later. */
  table: {
    insert: "إدراج جدول",
    edit: "تعديل الجدول",
    title: "الجدول",
    addRow: "إضافة صف",
    removeRow: "حذف آخر صف",
    addCol: "إضافة عمود",
    removeCol: "حذف آخر عمود",
    toLtr: "من اليسار لليمين",
    toRtl: "من اليمين لليسار",
    fill: "لون الخلية:",
    noFill: "بلا لون",
    merge: "دمج الخلايا",
    split: "تقسيم الخلية",
    mergeHint: "لدمج خلايا: اضغط خلية، ثم Shift مع الضغط على خلية أخرى — أو Ctrl+Shift مع الأسهم.",
    /** Read out as the selection grows: «٢ في ٣», rows by columns — no counted noun. */
    selection: (rows: number, cols: number) => `محدَّد ${arabicNumber(rows)} في ${arabicNumber(cols)}`,
    cell: (row: number, col: number) => `الصف ${arabicNumber(row)}، العمود ${arabicNumber(col)}`,
    save: "حفظ",
    cancel: "إلغاء",
    gone: "لم يعد الجدول على الصفحة، فلم يُحفظ التعديل.",
  },
  /** Story 6: an equation, written in MathLive or LaTeX and drawn by MathJax. */
  /** The floating scientific calculator. */
  calc: {
    open: "آلة حاسبة",
    title: "الآلة الحاسبة",
    input: "المسألة",
    result: "الناتج",
    angle: "الزوايا بالدرجات أو بالراديان",
    history: "السجل",
    noHistory: "لا عمليات بعد.",
    close: "إغلاق الآلة الحاسبة",
    toggleForm: "كسر أو عشري",
    insert: "حطّها على السبّورة",
    syntaxError: "خطأ في الكتابة",
    mathError: "خطأ رياضي",
  },
  math: {
    insert: "إدراج معادلة",
    edit: "تعديل المعادلة",
    title: "المعادلة",
    field: "المعادلة",
    latex: "أو اكتبها بصيغة LaTeX:",
    chemistryHint: "للكيمياء: \\ce{2H2 + O2 -> 2H2O}",
    display: "في سطر مستقل (أكبر وأوضح)",
    invalid: "المعادلة فيها خطأ في الكتابة. راجع الأوامر.",
    save: "إدراج",
    cancel: "إلغاء",
  },
  /** The academy's shared board library, a tab in Excalidraw's «مكتبة». */
  academy: {
    tab: "الأكاديمية",
    title: "مكتبة الأكاديمية",
    intro: "أشكال يشاركها مدرّسو الأكاديمية. اضغط شكلًا لتضعه على السبّورة، أو اسحبه إليها.",
    name: "اسم الشكل",
    share: "شارك المحدَّد مع الأكاديمية",
    selectFirst: "حدّد أشكالًا على السبّورة أولًا، ثم اكتب لها اسمًا.",
    empty: "لم يشارك أحدٌ شكلًا بعد.",
    sharedBy: (name: string) => `شاركه ${name}`,
    remove: "حذف",
    confirmRemove: "اضغط مرة أخرى للحذف",
    loadFailed: "تعذّر تحميل مكتبة الأكاديمية.",
    tooLarge: "الشكل كبير جدًّا للمشاركة. شارك جزءًا أصغر.",
    full: "مكتبة الأكاديمية ممتلئة. احذفوا أشكالًا قديمة أولًا.",
    pictures: "الصور لا تُشارك مع الأكاديمية؛ شاركنا الباقي.",
  },
  /** A graph of functions, drawn from them (mathjs) and edited again later. */
  graph: {
    insert: "رسم دالة",
    edit: "تعديل الرسم",
    title: "رسم الدوال",
    hint: "اكتب الدالة بالحروف الإنجليزية، مثل:",
    examples: ["x^2 - 3", "2*x + 1", "sin(x)", "sqrt(x)", "abs(x)", "1/x"],
    fn: (n: number) => `الدالة ${arabicNumber(n)}`,
    addFn: "إضافة دالة",
    remove: "حذف",
    invalid: "لم أفهم هذه الدالة. اكتبها بدلالة x، مثل x^2 - 3.",
    xRange: "مدى x:",
    yRange: "مدى y:",
    yAuto: "تلقائي",
    from: "من",
    to: "إلى",
    degrees: "الزوايا بالدرجات",
    points: "نقاط على الرسم:",
    addPoint: "إضافة نقطة",
    pointX: (n: number) => `س للنقطة ${arabicNumber(n)}`,
    pointY: (n: number) => `ص للنقطة ${arabicNumber(n)}`,
    pointLabel: (n: number) => `اسم النقطة ${arabicNumber(n)}`,
    preview: "معاينة الرسم",
    save: "إدراج",
    cancel: "إلغاء",
  },
  /** Story 5: the whole board as a PDF in a lesson's attachments. */
  lessonExport: {
    course: "الكورس",
    lesson: "الدرس",
    chooseCourse: "اختر الكورس",
    chooseLesson: "اختر الدرس",
    noLessons: "لا توجد دروس في هذا الكورس.",
    attach: "إرفاق السبّورة بمواد الدرس",
    replace: "استبدال المرفق بنسخة أحدث",
    attachedAlready: "السبّورة مرفقة بهذا الدرس. الإرفاق ثانيةً يستبدل الملف القديم.",
    askTeacher: "السبّورة مرفقة بهذا الدرس، واستبدالها يحتاج صلاحية حذف الدروس. اطلب من مدرّس الكورس.",
    drawing: (n: number, total: number) => `جارٍ تجهيز الصفحة ${arabicNumber(n)} من ${arabicNumber(total)}…`,
    uploading: "جارٍ رفع الملف…",
    attached: "أُرفقت السبّورة بالدرس، ويراها الطلاب في مرفقاته.",
    replaced: "استُبدل المرفق بالنسخة الأحدث.",
    failed: "تعذّر إرفاق السبّورة بالدرس. أعد المحاولة.",
    takenElsewhere: "أُرفقت السبّورة بهذا الدرس من نافذة أخرى. اضغط مرة ثانية لاستبدالها.",
  },
  importing: {
    choose: "اختر ملف PDF أو صورة",
    hint: "تُضاف بعد الصفحة الحالية: كل صفحة من الـ PDF صفحة، والصورة صفحة.",
    reading: "جارٍ فتح الملف…",
    converting: (n: number, total: number) => `جارٍ إضافة الصفحة ${arabicNumber(n)} من ${arabicNumber(total)}…`,
    capped: (max: number) => `الملف أطول من ذلك، فأُضيفت أول ${counted(max, NOUNS.pages)} منه فقط.`,
    done: (n: number) => `أُضيف ${counted(n, NOUNS.pages)}.`,
  },
  panels: { board: "لوحة السبّورة", tools: "أدوات الرسم", pages: "الصفحات", zoom: "التكبير والتراجع", library: "المكتبة والقائمة" },
  panelModes: { shown: "ظاهرة", folded: "مطويّة", auto: "تظهر لما تقرّب" },
  panelUnfold: (name: string) => `▾ ${name}`,

  /** Teaching tools (US9). */
  tools: {
    template: "خلفية الصفحة",
    templates: {
      none: "بلا",
      lined: "مسطّرة",
      grid: "مربّعات",
      dotted: "منقّطة",
      isometric: "متساوية القياس",
      graph: "رسم بياني",
      "arabic-lines": "كرّاسة عربية",
      music: "مدرج موسيقي",
    },
    pen: "القلم",
    insert: "إدراج",
    pens: { marker: "ماركر", brush: "فرشاة عريضة", highlighter: "قلم تظليل", magic: "قلم سحري ✦" },
    magicHint: "ارسم دائرة أو مربعاً أو سهماً، ويتحوّل لشكل مضبوط.",
    passing: "أدوات مؤقّتة",
    names: { magnifier: "عدسة", curtain: "ستارة", wheel: "عجلة الاختيار" },
    curtain: "حافة الستارة: اسحبها لكشف ما تحتها",
    reveal: "اكشف قليلاً",
    closeCurtain: "إزالة الستارة",
    wheelNames: "الأسماء، اسم في كل سطر (أو رقم واحد مثل ٣٠):",
    wheelPlaceholder: "أحمد\nمريم\nيوسف",
    wheelNoRepeat: "بدون تكرار حتى تنتهي الجولة",
    wheelLast: (name: string) => `الأخير: ${name}`,
    wheelOrder: "ترتيب الاختيار",
    wheelNewRound: "جولة جديدة",
    wheelNoPicks: "لم يُختر أحد بعد.",
    spin: "أدر العجلة",
    closeWheel: "إغلاق",
    geometry: "هندسة",
    instruments: { ruler: "مسطرة", protractor: "منقلة", compass: "فرجار", "set-square": "مثلث قائم" },
    turn: "اسحب لتدوير الأداة",
    open: "اسحب لفتح الفرجار",
    cm: "سم",
    closeInstrument: "إزالة الأداة",
  },

  /** The presenter's tools (US8). */
  presenter: {
    title: "عرض",
    laser: "ليزر",
    spotlight: "كشّاف",
    spotlightOff: "إطفاء الكشّاف",
    spotlightOn: "الكشّاف يعمل: [ و ] لتصغير الدائرة وتكبيرها، وEsc لإطفائه",
    timer: "مؤقّت",
    minutes: (n: number) => counted(n, NOUNS.minutes),
    pause: "إيقاف مؤقّت",
    resume: "متابعة",
    closeTimer: "إغلاق",
    timeUp: "انتهى الوقت",
  },

  /** Encouragement and pointer effects (US10, US12). */
  effects: {
    title: "تشجيع",
    groups: { praise: "تشجيع", order: "تنبيه", fun: "هزار" },
    names: {
      applause: "تصفيق",
      balloons: "بالونات",
      party: "احتفال",
      stars: "نجوم",
      drumroll: "طبلة",
      attention: "انتباه",
      hearts: "قلوب",
      thumbs: "إعجاب",
      bubbles: "فقاعات",
      airplane: "طيارة بهدية",
      egg: "بيضة",
      tomato: "طماطم",
      brick: "طوبة",
      whistle: "صفّارة",
      stick: "عصا المعلم",
      warning: "تحذير",
      wrong: "خطأ",
      yellowCard: "كارت أصفر",
      redCard: "كارت أحمر",
    },
    warning: "تنبيه!",
    attention: "انتباه!",
    popBalloon: "فرقع البالونة",
    stickers: "ملصق",
    sound: "صوت المؤثرات",
    soundHint: "يسمعه الطلاب فقط إذا شاركت صوت التبويب مع الشاشة.",
    trail: "أثر المؤشّر",
    trails: { off: "بلا أثر", neon: "نيون", sparks: "شرارات", rainbow: "ألوان" },
  },

  /** The pages strip (US3). */
  pagesTitle: "صفحات السبّورة",
  showPages: "الصفحات",
  pagesFold: "اطوِ قائمة الصفحات",
  pagesUnfold: "افتح قائمة الصفحات",
  pagesTotal: (total: number) => `من ${arabicNumber(total)}`,
  pageWord: "صفحة",
  screenWord: "شاشة",
  pageNumber: (n: number) => `صفحة ${arabicNumber(n)}`,
  addPage: "صفحة جديدة",
  duplicatePage: "نسخ",
  deletePage: "حذف",
  confirmDeletePage: "تأكيد الحذف",
  moveUp: "انقل الصفحة لأعلى",
  moveDown: "انقل الصفحة لأسفل",
  imageFailed: "تعذّر رفع الصورة. الصيغ المقبولة: PNG وJPEG، وحاول مرة أخرى.",
  pagesFailed: "تعذّر تعديل الصفحات. أعد المحاولة.",
  pageArriving: "الصفحة في الطريق…",

  duplicateBoard: "نسخ السبّورة",
  copying: "جارٍ النسخ… ستظهر النسخة في القائمة بعد لحظات.",
  deleteBoard: "حذف السبّورة",
  confirmDeleteBoard: "اضغط مرة أخرى لحذف السبّورة نهائياً",

  /** The save indicator's five states (US2). */
  saveState: {
    saved: "محفوظ",
    saving: "جارٍ الحفظ…",
    offline: "بدون اتصال — محفوظ على هذا الجهاز",
    failed: "تعذّر الحفظ",
    unprotected: "محفوظ — الحماية من الانقطاع غير متاحة في هذا المتصفّح",
  },

  readOnly: "للقراءة فقط",
  editingNow: (name: string) => `يحرّر الآن: ${name}`,
  takeEditing: "خُذ التحرير",
  takingEditing: "ينتقل التحرير إليك خلال ثوانٍ…",
  handoverNotice: "طلب مدرّس الكورس التحرير. تُحفظ تغييراتك ثم تصير السبّورة للقراءة فقط.",

  conflictTitle: "هذه الصفحة تغيّرت في مكان آخر",
  conflictMessage: "حُفظت نسخة أحدث من هذه الصفحة من تبويب أو جهاز آخر. اختر ما تريد الاحتفاظ به.",
  takeServerCopy: "خذ نسخة الخادم",
  keepMineAsNewPage: "احفظ نسختي كصفحة جديدة",

  restoreTitle: "وُجدت تغييرات لم تُحفظ على هذا الجهاز",
  restoreMessage: "آخر ما رسمته لم يصل إلى الخادم. «إلغاء» يعرض نسخة الخادم ويُبقي نسختك على الجهاز.",
  restoreAskMessage:
    "آخر ما رسمته لم يصل إلى الخادم، والصفحة تغيّرت على الخادم بعده. استعادة نسختك تحلّ محلّ نسخة الخادم. «إلغاء» يعرض نسخة الخادم ويُبقي نسختك على الجهاز.",
  restoreMine: "استعِد تغييراتي",

  /** The failure codes of contracts/api.md, one sentence each. */
  errors: {
    too_large: "الملف أكبر من الحدّ المسموح.",
    too_many_pages: "عدد الصفحات أكبر من الحدّ المسموح لهذه السبّورة.",
    unsupported: "صيغة الملف غير مدعومة. المقبول: PDF أو صورة PNG أو JPEG. احفظ العرض أو المستند PDF أولاً.",
    corrupt: "تعذّرت قراءة الملف. تأكّد أنه PDF سليم وغير محمي بكلمة سر.",
    scene_too_large: "محتوى هذه الصفحة أكبر من الحدّ المسموح. قسّمه على صفحتين.",
    board_too_large: "مجموع صفحات السبّورة أكبر من الحدّ المسموح. ابدأ سبّورة جديدة.",
    inline_file: "تعذّر حفظ صورة في الصفحة. أعد إدراجها.",
    unknown_file: "صورة في الصفحة لم تكتمل بعد. انتظر لحظة ثم احفظ.",
    bad_link: "رابط في الصفحة غير مسموح. الروابط المسموحة تبدأ بـ http أو https.",
    bad_element: "عنصر في الصفحة غير مدعوم.",
    lock_lost: "انتقل التحرير إلى مستخدم آخر. صارت السبّورة للقراءة فقط.",
    version_conflict: "حُفظت نسخة أحدث من هذه الصفحة في مكان آخر.",
    pages_changed: "تغيّرت صفحات السبّورة في مكان آخر. أُعيد تحميل الترتيب.",
    operation_pending: "عملية أخرى جارية على هذه السبّورة. انتظر لحظة.",
    already_exported: "هذه السبّورة مرفقة بالدرس من قبل.",
    replace_forbidden: "استبدال المرفق يحتاج صلاحية حذف الدروس. اطلب من مدرّس الكورس.",
    asset_not_ready: "الملف لم يكتمل رفعه بعد.",
    asset_mismatch: "هذا الملف لا يخصّ هذا الدرس.",
    last_page: "لا يمكن حذف الصفحة الأخيرة.",
  },
} as const;

export type WbErrorCode = keyof typeof WB.errors;
