<?php

declare(strict_types=1);

namespace App\Modules\LiveSessions\Actions;

use App\Modules\Courses\Models\Course;
use App\Modules\LiveSessions\Enums\ClassSessionStatus;
use App\Modules\LiveSessions\Models\ClassSession;
use App\Shared\Actions\Action;
use App\Shared\Contracts\CohortDirectory;
use DomainException;
use Illuminate\Support\Facades\DB;

/**
 * Files a batch of sessions under a group (FR-025هـ).
 *
 * ⚠️ ONE ACTION FOR THE WHOLE BATCH, NEVER A LOOP AT THE CLIENT. Forty requests
 * are forty chances for one to fail in the middle, leaving half the timetable
 * hidden with nothing to say which half — the rule 018 wrote down for the host's
 * bulk controls, arriving here for the same reason.
 *
 * ⚠️ AND A SESSION THAT HAS STARTED OR ENDED IS REFUSED (FR-025و). Assigning
 * after the fact only CLASSIFIES a session; it cannot redistribute the rights it
 * already handed out. Somebody attended that hour, somebody holds its recording
 * by the seat they bought, and filing it under a group they are not in would
 * take those away with a bookkeeping edit.
 *
 * ⚠️ THE WHOLE BATCH IS REFUSED RATHER THAN PART OF IT. A partial assignment
 * leaves the teacher with a shorter list and no idea which rows moved — and the
 * list they are working from is generated by this module, so an ineligible row
 * in it is a bug worth surfacing rather than skipping quietly.
 */
class AssignSessionsToCohort extends Action
{
    public function __construct(
        private readonly CohortDirectory $cohorts,
    ) {}

    /**
     * @param  list<string>  $sessionUuids
     * @return int how many were assigned
     */
    public function handle(Course $course, string $cohortUuid, array $sessionUuids): int
    {
        $cohortId = $this->cohorts->resolveCohortId($cohortUuid, (int) $course->getKey());

        if ($cohortId === null) {
            throw new DomainException('هذه المجموعة ليست من هذا الكورس.');
        }

        if ($sessionUuids === []) {
            return 0;
        }

        $sessions = ClassSession::query()
            ->where('course_id', $course->getKey())
            ->whereIn('uuid', $sessionUuids)
            ->get(['id', 'uuid', 'status', 'starts_at']);

        if ($sessions->count() !== count(array_unique($sessionUuids))) {
            throw new DomainException('بعض الحصص المطلوبة ليست من هذا الكورس.');
        }

        $blocked = $sessions->filter(
            fn (ClassSession $session): bool => $session->starts_at->isPast()
                || $session->status !== ClassSessionStatus::Scheduled,
        );

        if ($blocked->isNotEmpty()) {
            throw new DomainException(
                'لا يمكن إسناد حصة بدأت أو انتهت — عددها '.$blocked->count().'.',
            );
        }

        return DB::transaction(fn (): int => ClassSession::query()
            ->whereIn('id', $sessions->modelKeys())
            ->update(['cohort_id' => $cohortId]));
    }
}
