import type { Metadata } from "next";

import { PageBanner } from "@/components/ui/PageBanner";
import { ShieldIcon } from "@/components/icons";

export const metadata: Metadata = {
  title: "سياسة الخصوصية",
};

/**
 * The policy itself, publicly readable (spec 013 · FR-004).
 *
 * ⚠️ IT STAYS PUBLIC AND IT STAYS AT THIS PATH. The page already existed, showing
 * `PolicyPlaceholder` — "the text has not been written yet" — and it is linked
 * from every footer. Putting the real policy behind authentication would leave a
 * visitor reading that placeholder for ever, and would put TWO routes in the
 * product called `privacy`: this one and the signed-in `/privacy` where a person
 * manages their own requests. Those are different pages for different questions.
 *
 * ⚠️ AND `robots: { index: false }` IS GONE, deliberately. A privacy policy that
 * asks search engines not to list it is not published in any meaningful sense —
 * the placeholder had that flag because there was nothing worth finding.
 *
 * The text is rendered SERVER-SIDE from the API, which renders Markdown per
 * response and strips raw HTML rather than escaping it (016's rule): the allowlist
 * is the Markdown feature set, so there is no sanitiser configuration to get wrong
 * and no stored HTML column to drift from its source.
 */
export const revalidate = 300;

async function policy(): Promise<{ version: string; body_html: string } | null> {
  try {
    const response = await fetch(`${process.env.API_URL ?? "http://localhost:8000"}/api/v1/privacy/policy`, {
      headers: { Accept: "application/json" },
      next: { revalidate: 300 },
    });

    if (!response.ok) {
      return null;
    }

    return (await response.json()) as { version: string; body_html: string };
  } catch {
    /*
     * ⚠️ NULL, NOT A THROW. This page is linked from every footer on the site; an
     * API hiccup must not take the whole public shell down with it. The fallback
     * below says plainly that the text could not be loaded rather than rendering
     * an empty policy, which would be worse than an error — it would read as a
     * platform that collects nothing.
     */
    return null;
  }
}

export default async function PrivacyPage() {
  const document = await policy();

  return (
    <div className="space-y-6">
      <PageBanner
        icon={ShieldIcon}
        image="/marketplace/banner-privacy.webp"
        title="سياسة الخصوصية"
        description="ما البيانات التي نجمعها، ولماذا، ومن يطّلع عليها، وكيف تطلب حذفها."
      />

      {document === null ? (
        <p className="text-sm text-ink-muted">
          تعذّر تحميل نصّ السياسة الآن. أعد المحاولة بعد قليل.
        </p>
      ) : (
        <>
          {/*
            The rendered Markdown. `dangerouslySetInnerHTML` is safe here for one
            specific reason and not in general: the HTML comes from our own
            `MarkdownRenderer`, which STRIPS raw HTML from the source instead of
            escaping it — so nothing an author writes can produce a tag that was
            not generated by the Markdown grammar itself.
          */}
          <article
            className="prose-policy text-ink"
            dangerouslySetInnerHTML={{ __html: document.body_html }}
          />

          {/*
            ⚠️ THE VERSION IS SHOWN, and that is not decoration. A consent names
            the version it was given for, and publishing a new one invalidates
            every earlier acceptance on the next request — so a reader has to be
            able to tell which text they are looking at.
          */}
          <p className="text-xs text-ink-muted">نسخة السياسة: {document.version}</p>
        </>
      )}
    </div>
  );
}
